[build]
builder = "paketobuildpacks/builder:base"

[deploy]
startCommand = "vendor/bin/heroku-php-apache2 public/"

[env]
APP_ENV = "production"
APP_DEBUG = "false"
APP_URL = "https://kkn.dandy.my.id"
LOG_CHANNEL = "stderr"
DB_CONNECTION = "pgsql"
CACHE_DRIVER = "file"
SESSION_DRIVER = "file"
SESSION_LIFETIME = "120"
SESSION_ENCRYPT = "false"
SESSION_HTTP_ONLY = "true"
SESSION_SAME_SITE = "lax"
QUEUE_CONNECTION = "sync"
FORCE_HTTPS = "true"
SESSION_SECURE_COOKIE = "true"

[build.env]
COMPOSER_INSTALL_OPTIONS = "--no-dev --optimize-autoloader"
BP_PHP_VERSION = "8.2.*"